option(WITH_ZLIB "Build with ZLIB support" ON)
option(WITH_LIBEVENT "Build with libevent support" ON)
option(WITH_OPENSSL "Build with OpenSSL support" ON)
option(WITH_BOOSTTHREADS "Build with Boost thread support" OFF)
option(WITH_STATIC_LIB "Build with a static library" ON)
option(WITH_DEBUG_CRYPTO "Build with cryto debug output" OFF)
option(WITH_DEBUG_CALLTRACE "Build with calltrace debug output" ON)
option(WITH_INTERNAL_DOC "Compile doxygen internal documentation" OFF)
option(WITH_TESTING "Build with unit tests" OFF)
option(WITH_CLIENT_TESTING "Build with client tests; requires a running sshd" OFF)
option(WITH_BENCHMARKS "Build benchmarks tools" OFF)
option(WITH_EXAMPLES "Build examples" ON)

option(FORCE_STDTHREADS "Force the use of std::thread" OFF)

if (WITH_ZLIB)
    set(WITH_LIBZ ON)
else (WITH_ZLIB)
    set(WITH_LIBZ OFF)
endif (WITH_ZLIB)

if(WITH_BENCHMARKS)
  set(WITH_TESTING ON)
endif(WITH_BENCHMARKS)

if (WITH_TESTING)
  set(WITH_STATIC_LIB ON)
endif (WITH_TESTING)
